version: '3.8'
services:
  webserver:
    image: nginx:stable
    # o modo de rede deve ser especificado por serviço
    network_mode: bridge
    container_name: curso-nginx-alura
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./static:/usr/share/nginx/static
    ports:
      - 80:80
      - 8000:8000
      - 8001:8001
      - 8002:8002
      - 8003:8003
      - 8004:8004